"""cluster: suivi de la validation humaine

Revision ID: 14b87224537c
Revises: b7124bbd9d14
Create Date: 2026-09-12 08:10:47.546312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14b87224537c'
down_revision: Union[str, Sequence[str], None] = 'b7124bbd9d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cluster_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_foreign_key('fk_cluster_reviewed_by_id', 'user', ['reviewed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cluster_reviewed_by_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cluster_reviewed_at'))
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('reviewed_at')

    # ### end Alembic commands ###
