"""clustering semantique: tables cluster et clustering_run

Revision ID: b7124bbd9d14
Revises: 1f3a743ea256
Create Date: 2026-09-12 00:32:12.976409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b7124bbd9d14'
down_revision: Union[str, Sequence[str], None] = '1f3a743ea256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clustering_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('distance_threshold', sa.Float(), nullable=False),
    sa.Column('linkage', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('noise_pattern', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('keyword_count', sa.Integer(), nullable=False),
    sa.Column('cluster_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clustering_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clustering_run_created_at'), ['created_at'], unique=False)

    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('head_keyword_id', sa.Integer(), nullable=True),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('to_create', 'published', 'to_merge', 'discarded', name='clusterstatus'), server_default='to_create', nullable=False),
    sa.Column('keyword_count', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['head_keyword_id'], ['keyword.id'], use_alter=True),
    sa.ForeignKeyConstraint(['run_id'], ['clustering_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cluster_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_target_url'), ['target_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_total_volume'), ['total_volume'], unique=False)

    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cluster_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cluster_source', sa.Enum('unset', 'auto', 'manual', name='clustersource'), server_default='unset', nullable=False))
        batch_op.drop_index(batch_op.f('ix_keyword_cluster'))
        batch_op.create_index(batch_op.f('ix_keyword_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_cluster_source'), ['cluster_source'], unique=False)
        batch_op.create_foreign_key('fk_keyword_cluster_id', 'cluster', ['cluster_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.drop_constraint('fk_keyword_cluster_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_keyword_cluster_source'))
        batch_op.drop_index(batch_op.f('ix_keyword_cluster_id'))
        batch_op.create_index(batch_op.f('ix_keyword_cluster'), ['cluster'], unique=False)
        batch_op.drop_column('cluster_source')
        batch_op.drop_column('cluster_id')

    with op.batch_alter_table('cluster', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cluster_total_volume'))
        batch_op.drop_index(batch_op.f('ix_cluster_target_url'))
        batch_op.drop_index(batch_op.f('ix_cluster_status'))
        batch_op.drop_index(batch_op.f('ix_cluster_run_id'))

    op.drop_table('cluster')
    with op.batch_alter_table('clustering_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clustering_run_created_at'))

    op.drop_table('clustering_run')
    # ### end Alembic commands ###
