"""cluster_page: une page par cluster et par langue

Revision ID: cf5ac6043491
Revises: 14b87224537c
Create Date: 2026-09-12 08:41:10.102962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf5ac6043491'
down_revision: Union[str, Sequence[str], None] = '14b87224537c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('lang', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('head_keyword_id', sa.Integer(), nullable=True),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('proposed_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('to_create', 'published', 'to_merge', 'discarded', name='clusterstatus'), server_default='to_create', nullable=False),
    sa.Column('keyword_count', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['head_keyword_id'], ['keyword.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'lang', name='uq_cluster_page_lang')
    )
    with op.batch_alter_table('cluster_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cluster_page_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_page_lang'), ['lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_page_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_page_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cluster_page_target_url'), ['target_url'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cluster_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cluster_page_target_url'))
        batch_op.drop_index(batch_op.f('ix_cluster_page_status'))
        batch_op.drop_index(batch_op.f('ix_cluster_page_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_cluster_page_lang'))
        batch_op.drop_index(batch_op.f('ix_cluster_page_cluster_id'))

    op.drop_table('cluster_page')
    # ### end Alembic commands ###
